const manifest = {
  version: 1,

  base_dir: 'projetos',
  photoshoots: {
    Afrodite: [
      'Andressa/Andressa_1.webp',
      'Andressa/Andressa_2.webp',
      'Andressa/Andressa_3.webp',
      'Andressa/Andressa_4.webp',
      'Andressa/Andressa_5.webp',
      'Andressa/Andressa_6.webp',
      'isabel/arquivos sem edit/arquivos sem edit_1.webp',
      'isabel/arquivos sem edit/arquivos sem edit_10.webp',
      'isabel/arquivos sem edit/arquivos sem edit_11.webp',
      'isabel/arquivos sem edit/arquivos sem edit_12.webp',
      'isabel/arquivos sem edit/arquivos sem edit_13.webp',
      'isabel/arquivos sem edit/arquivos sem edit_14.webp',
      'isabel/arquivos sem edit/arquivos sem edit_15.webp',
      'isabel/arquivos sem edit/arquivos sem edit_16.webp',
      'isabel/arquivos sem edit/arquivos sem edit_17.webp',
      'isabel/arquivos sem edit/arquivos sem edit_18.webp',
      'isabel/arquivos sem edit/arquivos sem edit_19.webp',
      'isabel/arquivos sem edit/arquivos sem edit_2.webp',
      'isabel/arquivos sem edit/arquivos sem edit_20.webp',
      'isabel/arquivos sem edit/arquivos sem edit_21.webp',
      'isabel/arquivos sem edit/arquivos sem edit_22.webp',
      'isabel/arquivos sem edit/arquivos sem edit_23.webp',
      'isabel/arquivos sem edit/arquivos sem edit_24.webp',
      'isabel/arquivos sem edit/arquivos sem edit_25.webp',
      'isabel/arquivos sem edit/arquivos sem edit_26.webp',
      'isabel/arquivos sem edit/arquivos sem edit_27.webp',
      'isabel/arquivos sem edit/arquivos sem edit_28.webp',
      'isabel/arquivos sem edit/arquivos sem edit_29.webp',
      'isabel/arquivos sem edit/arquivos sem edit_3.webp',
      'isabel/arquivos sem edit/arquivos sem edit_30.webp',
      'isabel/arquivos sem edit/arquivos sem edit_31.webp',
      'isabel/arquivos sem edit/arquivos sem edit_32.webp',
      'isabel/arquivos sem edit/arquivos sem edit_33.webp',
      'isabel/arquivos sem edit/arquivos sem edit_34.webp',
      'isabel/arquivos sem edit/arquivos sem edit_35.webp',
      'isabel/arquivos sem edit/arquivos sem edit_36.webp',
      'isabel/arquivos sem edit/arquivos sem edit_37.webp',
      'isabel/arquivos sem edit/arquivos sem edit_38.webp',
      'isabel/arquivos sem edit/arquivos sem edit_39.webp',
      'isabel/arquivos sem edit/arquivos sem edit_4.webp',
      'isabel/arquivos sem edit/arquivos sem edit_40.webp',
      'isabel/arquivos sem edit/arquivos sem edit_41.webp',
      'isabel/arquivos sem edit/arquivos sem edit_42.webp',
      'isabel/arquivos sem edit/arquivos sem edit_43.webp',
      'isabel/arquivos sem edit/arquivos sem edit_44.webp',
      'isabel/arquivos sem edit/arquivos sem edit_45.webp',
      'isabel/arquivos sem edit/arquivos sem edit_46.webp',
      'isabel/arquivos sem edit/arquivos sem edit_47.webp',
      'isabel/arquivos sem edit/arquivos sem edit_48.webp',
      'isabel/arquivos sem edit/arquivos sem edit_49.webp',
      'isabel/arquivos sem edit/arquivos sem edit_5.webp',
      'isabel/arquivos sem edit/arquivos sem edit_50.webp',
      'isabel/arquivos sem edit/arquivos sem edit_51.webp',
      'isabel/arquivos sem edit/arquivos sem edit_52.webp',
      'isabel/arquivos sem edit/arquivos sem edit_53.webp',
      'isabel/arquivos sem edit/arquivos sem edit_54.webp',
      'isabel/arquivos sem edit/arquivos sem edit_55.webp',
      'isabel/arquivos sem edit/arquivos sem edit_56.webp',
      'isabel/arquivos sem edit/arquivos sem edit_57.webp',
      'isabel/arquivos sem edit/arquivos sem edit_58.webp',
      'isabel/arquivos sem edit/arquivos sem edit_59.webp',
      'isabel/arquivos sem edit/arquivos sem edit_6.webp',
      'isabel/arquivos sem edit/arquivos sem edit_60.webp',
      'isabel/arquivos sem edit/arquivos sem edit_61.webp',
      'isabel/arquivos sem edit/arquivos sem edit_62.webp',
      'isabel/arquivos sem edit/arquivos sem edit_63.webp',
      'isabel/arquivos sem edit/arquivos sem edit_64.webp',
      'isabel/arquivos sem edit/arquivos sem edit_65.webp',
      'isabel/arquivos sem edit/arquivos sem edit_66.webp',
      'isabel/arquivos sem edit/arquivos sem edit_67.webp',
      'isabel/arquivos sem edit/arquivos sem edit_68.webp',
      'isabel/arquivos sem edit/arquivos sem edit_69.webp',
      'isabel/arquivos sem edit/arquivos sem edit_7.webp',
      'isabel/arquivos sem edit/arquivos sem edit_70.webp',
      'isabel/arquivos sem edit/arquivos sem edit_71.webp',
      'isabel/arquivos sem edit/arquivos sem edit_72.webp',
      'isabel/arquivos sem edit/arquivos sem edit_73.webp',
      'isabel/arquivos sem edit/arquivos sem edit_74.webp',
      'isabel/arquivos sem edit/arquivos sem edit_75.webp',
      'isabel/arquivos sem edit/arquivos sem edit_76.webp',
      'isabel/arquivos sem edit/arquivos sem edit_77.webp',
      'isabel/arquivos sem edit/arquivos sem edit_78.webp',
      'isabel/arquivos sem edit/arquivos sem edit_79.webp',
      'isabel/arquivos sem edit/arquivos sem edit_8.webp',
      'isabel/arquivos sem edit/arquivos sem edit_80.webp',
      'isabel/arquivos sem edit/arquivos sem edit_81.webp',
      'isabel/arquivos sem edit/arquivos sem edit_9.webp',
      'isabel/isabel_1.webp',
      'isabel/isabel_2.webp',
      'isabel/isabel_3.webp',
      'isabel/isabel_4.webp',
      'mika/mika_1.webp',
      'mika/mika_10.webp',
      'mika/mika_11.webp',
      'mika/mika_12.webp',
      'mika/mika_13.webp',
      'mika/mika_14.webp',
      'mika/mika_15.webp',
      'mika/mika_16.webp',
      'mika/mika_17.webp',
      'mika/mika_18.webp',
      'mika/mika_19.webp',
      'mika/mika_2.webp',
      'mika/mika_20.webp',
      'mika/mika_21.webp',
      'mika/mika_22.webp',
      'mika/mika_23.webp',
      'mika/mika_24.webp',
      'mika/mika_25.webp',
      'mika/mika_26.webp',
      'mika/mika_27.webp',
      'mika/mika_28.webp',
      'mika/mika_29.webp',
      'mika/mika_3.webp',
      'mika/mika_30.webp',
      'mika/mika_4.webp',
      'mika/mika_5.webp',
      'mika/mika_6.webp',
      'mika/mika_7.webp',
      'mika/mika_8.webp',
      'mika/mika_9.webp',
      'milena/milena_1.webp',
      'milena/milena_10.webp',
      'milena/milena_11.webp',
      'milena/milena_2.webp',
      'milena/milena_3.webp',
      'milena/milena_4.webp',
      'milena/milena_5.webp',
      'milena/milena_6.webp',
      'milena/milena_7.webp',
      'milena/milena_8.webp',
      'milena/milena_9.webp',
      'PATY SCHMIDT/PATY SCHMIDT_1.webp',
      'PATY SCHMIDT/PATY SCHMIDT_2.webp',
      'PATY SCHMIDT/PATY SCHMIDT_3.webp',
      'PATY SCHMIDT/PATY SCHMIDT_4.webp',
      'PATY SCHMIDT/PATY SCHMIDT_5.webp',
      'paty_anie/paty_anie_1.webp',
      'paty_anie/paty_anie_2.webp',
      'paty_anie/paty_anie_3.webp',
      'paty_anie/paty_anie_4.webp',
      'paty_anie/paty_anie_5.webp',
      'tally/tally_1.webp',
      'tally/tally_2.webp',
      'tally/tally_3.webp',
      'tally/tally_4.webp',
      'tally/tally_5.webp',
    ],
    epoca: [
      'andressa/andressa_1.webp',
      'andressa/andressa_2.webp',
      'andressa/andressa_3.webp',
      'andressa/andressa_4.webp',
      'Anna_Julia/Anna_Julia_1.webp',
      'Anna_Julia/Anna_Julia_10.webp',
      'Anna_Julia/Anna_Julia_2.webp',
      'Anna_Julia/Anna_Julia_3.webp',
      'Anna_Julia/Anna_Julia_4.webp',
      'Anna_Julia/Anna_Julia_5.webp',
      'Anna_Julia/Anna_Julia_6.webp',
      'Anna_Julia/Anna_Julia_7.webp',
      'Anna_Julia/Anna_Julia_8.webp',
      'Anna_Julia/Anna_Julia_9.webp',
      'Bruna_Camargo/Bruna_Camargo_1.webp',
      'Bruna_Camargo/Bruna_Camargo_10.webp',
      'Bruna_Camargo/Bruna_Camargo_11.webp',
      'Bruna_Camargo/Bruna_Camargo_12.webp',
      'Bruna_Camargo/Bruna_Camargo_13.webp',
      'Bruna_Camargo/Bruna_Camargo_14.webp',
      'Bruna_Camargo/Bruna_Camargo_15.webp',
      'Bruna_Camargo/Bruna_Camargo_16.webp',
      'Bruna_Camargo/Bruna_Camargo_17.webp',
      'Bruna_Camargo/Bruna_Camargo_18.webp',
      'Bruna_Camargo/Bruna_Camargo_19.webp',
      'Bruna_Camargo/Bruna_Camargo_2.webp',
      'Bruna_Camargo/Bruna_Camargo_20.webp',
      'Bruna_Camargo/Bruna_Camargo_3.webp',
      'Bruna_Camargo/Bruna_Camargo_4.webp',
      'Bruna_Camargo/Bruna_Camargo_5.webp',
      'Bruna_Camargo/Bruna_Camargo_6.webp',
      'Bruna_Camargo/Bruna_Camargo_7.webp',
      'Bruna_Camargo/Bruna_Camargo_8.webp',
      'Bruna_Camargo/Bruna_Camargo_9.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_1.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_10.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_11.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_12.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_13.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_14.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_15.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_16.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_17.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_18.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_2.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_3.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_4.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_5.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_6.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_7.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_8.webp',
      'GLAUCIA & OLLIE/GLAUCIA & OLLIE_9.webp',
      'Hayanna/Hayanna_1.webp',
      'Hayanna/Hayanna_10.webp',
      'Hayanna/Hayanna_11.webp',
      'Hayanna/Hayanna_12.webp',
      'Hayanna/Hayanna_13.webp',
      'Hayanna/Hayanna_14.webp',
      'Hayanna/Hayanna_15.webp',
      'Hayanna/Hayanna_16.webp',
      'Hayanna/Hayanna_17.webp',
      'Hayanna/Hayanna_18.webp',
      'Hayanna/Hayanna_19.webp',
      'Hayanna/Hayanna_2.webp',
      'Hayanna/Hayanna_20.webp',
      'Hayanna/Hayanna_21.webp',
      'Hayanna/Hayanna_22.webp',
      'Hayanna/Hayanna_23.webp',
      'Hayanna/Hayanna_24.webp',
      'Hayanna/Hayanna_25.webp',
      'Hayanna/Hayanna_26.webp',
      'Hayanna/Hayanna_27.webp',
      'Hayanna/Hayanna_28.webp',
      'Hayanna/Hayanna_29.webp',
      'Hayanna/Hayanna_3.webp',
      'Hayanna/Hayanna_30.webp',
      'Hayanna/Hayanna_31.webp',
      'Hayanna/Hayanna_4.webp',
      'Hayanna/Hayanna_5.webp',
      'Hayanna/Hayanna_6.webp',
      'Hayanna/Hayanna_7.webp',
      'Hayanna/Hayanna_8.webp',
      'Hayanna/Hayanna_9.webp',
      'Heidi/Heidi_1.webp',
      'Heidi/Heidi_10.webp',
      'Heidi/Heidi_2.webp',
      'Heidi/Heidi_3.webp',
      'Heidi/Heidi_4.webp',
      'Heidi/Heidi_5.webp',
      'Heidi/Heidi_6.webp',
      'Heidi/Heidi_7.webp',
      'Heidi/Heidi_8.webp',
      'Heidi/Heidi_9.webp',
      'jessica/jessica_1.webp',
      'jessica/jessica_2.webp',
      'jessica/jessica_3.webp',
      'jessica/jessica_4.webp',
      'jessica/jessica_5.webp',
      'jessica/jessica_6.webp',
      'jessica/jessica_7.webp',
      'jessica/jessica_8.webp',
      'jessica/jessica_9.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_1.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_10.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_11.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_12.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_13.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_14.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_15.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_2.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_3.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_4.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_5.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_6.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_7.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_8.webp',
      'Nadia_Lobkov1/Nadia_Lobkov1_9.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_1.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_10.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_11.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_12.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_13.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_14.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_15.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_16.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_17.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_18.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_19.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_2.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_20.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_21.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_22.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_23.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_24.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_25.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_3.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_4.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_5.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_6.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_7.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_8.webp',
      'Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_9.webp',
      'Nayara_Luis/Nayara_Luis_1.webp',
      'Nayara_Luis/Nayara_Luis_10.webp',
      'Nayara_Luis/Nayara_Luis_11.webp',
      'Nayara_Luis/Nayara_Luis_12.webp',
      'Nayara_Luis/Nayara_Luis_13.webp',
      'Nayara_Luis/Nayara_Luis_14.webp',
      'Nayara_Luis/Nayara_Luis_15.webp',
      'Nayara_Luis/Nayara_Luis_16.webp',
      'Nayara_Luis/Nayara_Luis_17.webp',
      'Nayara_Luis/Nayara_Luis_18.webp',
      'Nayara_Luis/Nayara_Luis_19.webp',
      'Nayara_Luis/Nayara_Luis_2.webp',
      'Nayara_Luis/Nayara_Luis_20.webp',
      'Nayara_Luis/Nayara_Luis_21.webp',
      'Nayara_Luis/Nayara_Luis_22.webp',
      'Nayara_Luis/Nayara_Luis_23.webp',
      'Nayara_Luis/Nayara_Luis_24.webp',
      'Nayara_Luis/Nayara_Luis_25.webp',
      'Nayara_Luis/Nayara_Luis_26.webp',
      'Nayara_Luis/Nayara_Luis_27.webp',
      'Nayara_Luis/Nayara_Luis_28.webp',
      'Nayara_Luis/Nayara_Luis_29.webp',
      'Nayara_Luis/Nayara_Luis_3.webp',
      'Nayara_Luis/Nayara_Luis_30.webp',
      'Nayara_Luis/Nayara_Luis_31.webp',
      'Nayara_Luis/Nayara_Luis_32.webp',
      'Nayara_Luis/Nayara_Luis_33.webp',
      'Nayara_Luis/Nayara_Luis_34.webp',
      'Nayara_Luis/Nayara_Luis_4.webp',
      'Nayara_Luis/Nayara_Luis_5.webp',
      'Nayara_Luis/Nayara_Luis_6.webp',
      'Nayara_Luis/Nayara_Luis_7.webp',
      'Nayara_Luis/Nayara_Luis_8.webp',
      'Nayara_Luis/Nayara_Luis_9.webp',
      'Paloma/Paloma_1.webp',
      'Paloma/Paloma_10.webp',
      'Paloma/Paloma_11.webp',
      'Paloma/Paloma_2.webp',
      'Paloma/Paloma_3.webp',
      'Paloma/Paloma_4.webp',
      'Paloma/Paloma_5.webp',
      'Paloma/Paloma_6.webp',
      'Paloma/Paloma_7.webp',
      'Paloma/Paloma_8.webp',
      'Paloma/Paloma_9.webp',
      'Val/Val_1.webp',
      'Val/Val_10.webp',
      'Val/Val_2.webp',
      'Val/Val_3.webp',
      'Val/Val_4.webp',
      'Val/Val_5.webp',
      'Val/Val_6.webp',
      'Val/Val_7.webp',
      'Val/Val_8.webp',
      'Val/Val_9.webp',
    ],
    eventos: [
      'jheni e a cobra/jheni e a cobra_1.webp',
      'jheni e a cobra/jheni e a cobra_10.webp',
      'jheni e a cobra/jheni e a cobra_100.webp',
      'jheni e a cobra/jheni e a cobra_101.webp',
      'jheni e a cobra/jheni e a cobra_102.webp',
      'jheni e a cobra/jheni e a cobra_11.webp',
      'jheni e a cobra/jheni e a cobra_12.webp',
      'jheni e a cobra/jheni e a cobra_13.webp',
      'jheni e a cobra/jheni e a cobra_14.webp',
      'jheni e a cobra/jheni e a cobra_15.webp',
      'jheni e a cobra/jheni e a cobra_16.webp',
      'jheni e a cobra/jheni e a cobra_17.webp',
      'jheni e a cobra/jheni e a cobra_18.webp',
      'jheni e a cobra/jheni e a cobra_19.webp',
      'jheni e a cobra/jheni e a cobra_2.webp',
      'jheni e a cobra/jheni e a cobra_20.webp',
      'jheni e a cobra/jheni e a cobra_21.webp',
      'jheni e a cobra/jheni e a cobra_22.webp',
      'jheni e a cobra/jheni e a cobra_23.webp',
      'jheni e a cobra/jheni e a cobra_24.webp',
      'jheni e a cobra/jheni e a cobra_25.webp',
      'jheni e a cobra/jheni e a cobra_26.webp',
      'jheni e a cobra/jheni e a cobra_27.webp',
      'jheni e a cobra/jheni e a cobra_28.webp',
      'jheni e a cobra/jheni e a cobra_29.webp',
      'jheni e a cobra/jheni e a cobra_3.webp',
      'jheni e a cobra/jheni e a cobra_30.webp',
      'jheni e a cobra/jheni e a cobra_31.webp',
      'jheni e a cobra/jheni e a cobra_32.webp',
      'jheni e a cobra/jheni e a cobra_33.webp',
      'jheni e a cobra/jheni e a cobra_34.webp',
      'jheni e a cobra/jheni e a cobra_35.webp',
      'jheni e a cobra/jheni e a cobra_36.webp',
      'jheni e a cobra/jheni e a cobra_37.webp',
      'jheni e a cobra/jheni e a cobra_38.webp',
      'jheni e a cobra/jheni e a cobra_39.webp',
      'jheni e a cobra/jheni e a cobra_4.webp',
      'jheni e a cobra/jheni e a cobra_40.webp',
      'jheni e a cobra/jheni e a cobra_41.webp',
      'jheni e a cobra/jheni e a cobra_42.webp',
      'jheni e a cobra/jheni e a cobra_43.webp',
      'jheni e a cobra/jheni e a cobra_44.webp',
      'jheni e a cobra/jheni e a cobra_45.webp',
      'jheni e a cobra/jheni e a cobra_46.webp',
      'jheni e a cobra/jheni e a cobra_47.webp',
      'jheni e a cobra/jheni e a cobra_48.webp',
      'jheni e a cobra/jheni e a cobra_49.webp',
      'jheni e a cobra/jheni e a cobra_5.webp',
      'jheni e a cobra/jheni e a cobra_50.webp',
      'jheni e a cobra/jheni e a cobra_51.webp',
      'jheni e a cobra/jheni e a cobra_52.webp',
      'jheni e a cobra/jheni e a cobra_53.webp',
      'jheni e a cobra/jheni e a cobra_54.webp',
      'jheni e a cobra/jheni e a cobra_55.webp',
      'jheni e a cobra/jheni e a cobra_56.webp',
      'jheni e a cobra/jheni e a cobra_57.webp',
      'jheni e a cobra/jheni e a cobra_58.webp',
      'jheni e a cobra/jheni e a cobra_59.webp',
      'jheni e a cobra/jheni e a cobra_6.webp',
      'jheni e a cobra/jheni e a cobra_60.webp',
      'jheni e a cobra/jheni e a cobra_61.webp',
      'jheni e a cobra/jheni e a cobra_62.webp',
      'jheni e a cobra/jheni e a cobra_63.webp',
      'jheni e a cobra/jheni e a cobra_64.webp',
      'jheni e a cobra/jheni e a cobra_65.webp',
      'jheni e a cobra/jheni e a cobra_66.webp',
      'jheni e a cobra/jheni e a cobra_67.webp',
      'jheni e a cobra/jheni e a cobra_68.webp',
      'jheni e a cobra/jheni e a cobra_69.webp',
      'jheni e a cobra/jheni e a cobra_7.webp',
      'jheni e a cobra/jheni e a cobra_70.webp',
      'jheni e a cobra/jheni e a cobra_71.webp',
      'jheni e a cobra/jheni e a cobra_72.webp',
      'jheni e a cobra/jheni e a cobra_73.webp',
      'jheni e a cobra/jheni e a cobra_74.webp',
      'jheni e a cobra/jheni e a cobra_75.webp',
      'jheni e a cobra/jheni e a cobra_76.webp',
      'jheni e a cobra/jheni e a cobra_77.webp',
      'jheni e a cobra/jheni e a cobra_78.webp',
      'jheni e a cobra/jheni e a cobra_79.webp',
      'jheni e a cobra/jheni e a cobra_8.webp',
      'jheni e a cobra/jheni e a cobra_80.webp',
      'jheni e a cobra/jheni e a cobra_81.webp',
      'jheni e a cobra/jheni e a cobra_82.webp',
      'jheni e a cobra/jheni e a cobra_83.webp',
      'jheni e a cobra/jheni e a cobra_84.webp',
      'jheni e a cobra/jheni e a cobra_85.webp',
      'jheni e a cobra/jheni e a cobra_86.webp',
      'jheni e a cobra/jheni e a cobra_87.webp',
      'jheni e a cobra/jheni e a cobra_88.webp',
      'jheni e a cobra/jheni e a cobra_89.webp',
      'jheni e a cobra/jheni e a cobra_9.webp',
      'jheni e a cobra/jheni e a cobra_90.webp',
      'jheni e a cobra/jheni e a cobra_91.webp',
      'jheni e a cobra/jheni e a cobra_92.webp',
      'jheni e a cobra/jheni e a cobra_93.webp',
      'jheni e a cobra/jheni e a cobra_94.webp',
      'jheni e a cobra/jheni e a cobra_95.webp',
      'jheni e a cobra/jheni e a cobra_96.webp',
      'jheni e a cobra/jheni e a cobra_97.webp',
      'jheni e a cobra/jheni e a cobra_98.webp',
      'jheni e a cobra/jheni e a cobra_99.webp',
    ],
    musa_day: [
      'Andressa e a cobra/Andressa e a cobra_1.webp',
      'Andressa e a cobra/Andressa e a cobra_10.webp',
      'Andressa e a cobra/Andressa e a cobra_11.webp',
      'Andressa e a cobra/Andressa e a cobra_12.webp',
      'Andressa e a cobra/Andressa e a cobra_2.webp',
      'Andressa e a cobra/Andressa e a cobra_3.webp',
      'Andressa e a cobra/Andressa e a cobra_4.webp',
      'Andressa e a cobra/Andressa e a cobra_5.webp',
      'Andressa e a cobra/Andressa e a cobra_6.webp',
      'Andressa e a cobra/Andressa e a cobra_7.webp',
      'Andressa e a cobra/Andressa e a cobra_8.webp',
      'Andressa e a cobra/Andressa e a cobra_9.webp',
      'Daiara/Daiara_1.webp',
      'Daiara/Daiara_2.webp',
      'Daiara/Daiara_3.webp',
      'Daiara/Daiara_4.webp',
      'Daiara/Daiara_5.webp',
      'Daiara/Daiara_6.webp',
      'Daiara/Daiara_7.webp',
      'Monica e a coruja/Monica e a coruja_1.webp',
      'Monica e a coruja/Monica e a coruja_10.webp',
      'Monica e a coruja/Monica e a coruja_11.webp',
      'Monica e a coruja/Monica e a coruja_12.webp',
      'Monica e a coruja/Monica e a coruja_13.webp',
      'Monica e a coruja/Monica e a coruja_14.webp',
      'Monica e a coruja/Monica e a coruja_15.webp',
      'Monica e a coruja/Monica e a coruja_2.webp',
      'Monica e a coruja/Monica e a coruja_3.webp',
      'Monica e a coruja/Monica e a coruja_4.webp',
      'Monica e a coruja/Monica e a coruja_5.webp',
      'Monica e a coruja/Monica e a coruja_6.webp',
      'Monica e a coruja/Monica e a coruja_7.webp',
      'Monica e a coruja/Monica e a coruja_8.webp',
      'Monica e a coruja/Monica e a coruja_9.webp',
      'nadia e a cobra/nadia e a cobra_1.webp',
      'nadia e a cobra/nadia e a cobra_10.webp',
      'nadia e a cobra/nadia e a cobra_11.webp',
      'nadia e a cobra/nadia e a cobra_12.webp',
      'nadia e a cobra/nadia e a cobra_13.webp',
      'nadia e a cobra/nadia e a cobra_14.webp',
      'nadia e a cobra/nadia e a cobra_2.webp',
      'nadia e a cobra/nadia e a cobra_3.webp',
      'nadia e a cobra/nadia e a cobra_4.webp',
      'nadia e a cobra/nadia e a cobra_5.webp',
      'nadia e a cobra/nadia e a cobra_6.webp',
      'nadia e a cobra/nadia e a cobra_7.webp',
      'nadia e a cobra/nadia e a cobra_8.webp',
      'nadia e a cobra/nadia e a cobra_9.webp',
    ],
    'MUSAS MÍSTICAS ENSAIO EXTERNO': ['Malu/Malu_1.webp'],
    personalizados: [
      'Bella de Moraes/Bella de Moraes_1.webp',
      'Bella de Moraes/Bella de Moraes_10.webp',
      'Bella de Moraes/Bella de Moraes_2.webp',
      'Bella de Moraes/Bella de Moraes_3.webp',
      'Bella de Moraes/Bella de Moraes_4.webp',
      'Bella de Moraes/Bella de Moraes_5.webp',
      'Bella de Moraes/Bella de Moraes_6.webp',
      'Bella de Moraes/Bella de Moraes_7.webp',
      'Bella de Moraes/Bella de Moraes_8.webp',
      'Bella de Moraes/Bella de Moraes_9.webp',
      'jaci/jaci_1.webp',
      'jaci/jaci_10.webp',
      'jaci/jaci_11.webp',
      'jaci/jaci_12.webp',
      'jaci/jaci_13.webp',
      'jaci/jaci_14.webp',
      'jaci/jaci_15.webp',
      'jaci/jaci_16.webp',
      'jaci/jaci_2.webp',
      'jaci/jaci_3.webp',
      'jaci/jaci_4.webp',
      'jaci/jaci_5.webp',
      'jaci/jaci_6.webp',
      'jaci/jaci_7.webp',
      'jaci/jaci_8.webp',
      'jaci/jaci_9.webp',
      'keshy/keshy_1.webp',
      'keshy/keshy_10.webp',
      'keshy/keshy_11.webp',
      'keshy/keshy_12.webp',
      'keshy/keshy_13.webp',
      'keshy/keshy_14.webp',
      'keshy/keshy_15.webp',
      'keshy/keshy_16.webp',
      'keshy/keshy_17.webp',
      'keshy/keshy_18.webp',
      'keshy/keshy_19.webp',
      'keshy/keshy_2.webp',
      'keshy/keshy_20.webp',
      'keshy/keshy_21.webp',
      'keshy/keshy_22.webp',
      'keshy/keshy_23.webp',
      'keshy/keshy_24.webp',
      'keshy/keshy_25.webp',
      'keshy/keshy_26.webp',
      'keshy/keshy_27.webp',
      'keshy/keshy_28.webp',
      'keshy/keshy_29.webp',
      'keshy/keshy_3.webp',
      'keshy/keshy_30.webp',
      'keshy/keshy_31.webp',
      'keshy/keshy_32.webp',
      'keshy/keshy_33.webp',
      'keshy/keshy_34.webp',
      'keshy/keshy_35.webp',
      'keshy/keshy_36.webp',
      'keshy/keshy_4.webp',
      'keshy/keshy_5.webp',
      'keshy/keshy_6.webp',
      'keshy/keshy_7.webp',
      'keshy/keshy_8.webp',
      'keshy/keshy_9.webp',
      'Lara/Lara_1.webp',
      'Lara/Lara_10.webp',
      'Lara/Lara_11.webp',
      'Lara/Lara_12.webp',
      'Lara/Lara_13.webp',
      'Lara/Lara_14.webp',
      'Lara/Lara_15.webp',
      'Lara/Lara_16.webp',
      'Lara/Lara_17.webp',
      'Lara/Lara_18.webp',
      'Lara/Lara_19.webp',
      'Lara/Lara_2.webp',
      'Lara/Lara_20.webp',
      'Lara/Lara_21.webp',
      'Lara/Lara_22.webp',
      'Lara/Lara_3.webp',
      'Lara/Lara_4.webp',
      'Lara/Lara_5.webp',
      'Lara/Lara_6.webp',
      'Lara/Lara_7.webp',
      'Lara/Lara_8.webp',
      'Lara/Lara_9.webp',
      'Monica/Monica_1.webp',
      'Monica/Monica_10.webp',
      'Monica/Monica_11.webp',
      'Monica/Monica_12.webp',
      'Monica/Monica_13.webp',
      'Monica/Monica_14.webp',
      'Monica/Monica_15.webp',
      'Monica/Monica_2.webp',
      'Monica/Monica_3.webp',
      'Monica/Monica_4.webp',
      'Monica/Monica_5.webp',
      'Monica/Monica_6.webp',
      'Monica/Monica_7.webp',
      'Monica/Monica_8.webp',
      'Monica/Monica_9.webp',
    ],
  },
  all: [
    'projetos/Afrodite/Andressa/Andressa_1.webp',
    'projetos/Afrodite/Andressa/Andressa_2.webp',
    'projetos/Afrodite/Andressa/Andressa_3.webp',
    'projetos/Afrodite/Andressa/Andressa_4.webp',
    'projetos/Afrodite/Andressa/Andressa_5.webp',
    'projetos/Afrodite/Andressa/Andressa_6.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_1.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_10.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_11.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_12.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_13.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_14.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_15.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_16.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_17.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_18.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_19.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_2.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_20.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_21.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_22.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_23.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_24.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_25.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_26.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_27.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_28.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_29.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_3.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_30.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_31.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_32.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_33.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_34.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_35.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_36.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_37.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_38.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_39.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_4.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_40.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_41.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_42.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_43.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_44.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_45.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_46.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_47.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_48.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_49.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_5.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_50.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_51.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_52.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_53.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_54.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_55.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_56.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_57.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_58.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_59.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_6.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_60.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_61.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_62.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_63.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_64.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_65.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_66.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_67.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_68.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_69.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_7.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_70.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_71.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_72.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_73.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_74.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_75.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_76.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_77.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_78.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_79.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_8.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_80.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_81.webp',
    'projetos/Afrodite/isabel/arquivos sem edit/arquivos sem edit_9.webp',
    'projetos/Afrodite/isabel/isabel_1.webp',
    'projetos/Afrodite/isabel/isabel_2.webp',
    'projetos/Afrodite/isabel/isabel_3.webp',
    'projetos/Afrodite/isabel/isabel_4.webp',
    'projetos/Afrodite/mika/mika_1.webp',
    'projetos/Afrodite/mika/mika_10.webp',
    'projetos/Afrodite/mika/mika_11.webp',
    'projetos/Afrodite/mika/mika_12.webp',
    'projetos/Afrodite/mika/mika_13.webp',
    'projetos/Afrodite/mika/mika_14.webp',
    'projetos/Afrodite/mika/mika_15.webp',
    'projetos/Afrodite/mika/mika_16.webp',
    'projetos/Afrodite/mika/mika_17.webp',
    'projetos/Afrodite/mika/mika_18.webp',
    'projetos/Afrodite/mika/mika_19.webp',
    'projetos/Afrodite/mika/mika_2.webp',
    'projetos/Afrodite/mika/mika_20.webp',
    'projetos/Afrodite/mika/mika_21.webp',
    'projetos/Afrodite/mika/mika_22.webp',
    'projetos/Afrodite/mika/mika_23.webp',
    'projetos/Afrodite/mika/mika_24.webp',
    'projetos/Afrodite/mika/mika_25.webp',
    'projetos/Afrodite/mika/mika_26.webp',
    'projetos/Afrodite/mika/mika_27.webp',
    'projetos/Afrodite/mika/mika_28.webp',
    'projetos/Afrodite/mika/mika_29.webp',
    'projetos/Afrodite/mika/mika_3.webp',
    'projetos/Afrodite/mika/mika_30.webp',
    'projetos/Afrodite/mika/mika_4.webp',
    'projetos/Afrodite/mika/mika_5.webp',
    'projetos/Afrodite/mika/mika_6.webp',
    'projetos/Afrodite/mika/mika_7.webp',
    'projetos/Afrodite/mika/mika_8.webp',
    'projetos/Afrodite/mika/mika_9.webp',
    'projetos/Afrodite/milena/milena_1.webp',
    'projetos/Afrodite/milena/milena_10.webp',
    'projetos/Afrodite/milena/milena_11.webp',
    'projetos/Afrodite/milena/milena_2.webp',
    'projetos/Afrodite/milena/milena_3.webp',
    'projetos/Afrodite/milena/milena_4.webp',
    'projetos/Afrodite/milena/milena_5.webp',
    'projetos/Afrodite/milena/milena_6.webp',
    'projetos/Afrodite/milena/milena_7.webp',
    'projetos/Afrodite/milena/milena_8.webp',
    'projetos/Afrodite/milena/milena_9.webp',
    'projetos/Afrodite/PATY SCHMIDT/PATY SCHMIDT_1.webp',
    'projetos/Afrodite/PATY SCHMIDT/PATY SCHMIDT_2.webp',
    'projetos/Afrodite/PATY SCHMIDT/PATY SCHMIDT_3.webp',
    'projetos/Afrodite/PATY SCHMIDT/PATY SCHMIDT_4.webp',
    'projetos/Afrodite/PATY SCHMIDT/PATY SCHMIDT_5.webp',
    'projetos/Afrodite/paty_anie/paty_anie_1.webp',
    'projetos/Afrodite/paty_anie/paty_anie_2.webp',
    'projetos/Afrodite/paty_anie/paty_anie_3.webp',
    'projetos/Afrodite/paty_anie/paty_anie_4.webp',
    'projetos/Afrodite/paty_anie/paty_anie_5.webp',
    'projetos/Afrodite/tally/tally_1.webp',
    'projetos/Afrodite/tally/tally_2.webp',
    'projetos/Afrodite/tally/tally_3.webp',
    'projetos/Afrodite/tally/tally_4.webp',
    'projetos/Afrodite/tally/tally_5.webp',
    'projetos/epoca/andressa/andressa_1.webp',
    'projetos/epoca/andressa/andressa_2.webp',
    'projetos/epoca/andressa/andressa_3.webp',
    'projetos/epoca/andressa/andressa_4.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_1.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_10.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_2.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_3.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_4.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_5.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_6.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_7.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_8.webp',
    'projetos/epoca/Anna_Julia/Anna_Julia_9.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_1.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_10.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_11.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_12.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_13.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_14.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_15.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_16.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_17.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_18.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_19.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_2.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_20.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_3.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_4.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_5.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_6.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_7.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_8.webp',
    'projetos/epoca/Bruna_Camargo/Bruna_Camargo_9.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_1.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_10.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_11.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_12.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_13.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_14.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_15.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_16.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_17.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_18.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_2.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_3.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_4.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_5.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_6.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_7.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_8.webp',
    'projetos/epoca/GLAUCIA & OLLIE/GLAUCIA & OLLIE_9.webp',
    'projetos/epoca/Hayanna/Hayanna_1.webp',
    'projetos/epoca/Hayanna/Hayanna_10.webp',
    'projetos/epoca/Hayanna/Hayanna_11.webp',
    'projetos/epoca/Hayanna/Hayanna_12.webp',
    'projetos/epoca/Hayanna/Hayanna_13.webp',
    'projetos/epoca/Hayanna/Hayanna_14.webp',
    'projetos/epoca/Hayanna/Hayanna_15.webp',
    'projetos/epoca/Hayanna/Hayanna_16.webp',
    'projetos/epoca/Hayanna/Hayanna_17.webp',
    'projetos/epoca/Hayanna/Hayanna_18.webp',
    'projetos/epoca/Hayanna/Hayanna_19.webp',
    'projetos/epoca/Hayanna/Hayanna_2.webp',
    'projetos/epoca/Hayanna/Hayanna_20.webp',
    'projetos/epoca/Hayanna/Hayanna_21.webp',
    'projetos/epoca/Hayanna/Hayanna_22.webp',
    'projetos/epoca/Hayanna/Hayanna_23.webp',
    'projetos/epoca/Hayanna/Hayanna_24.webp',
    'projetos/epoca/Hayanna/Hayanna_25.webp',
    'projetos/epoca/Hayanna/Hayanna_26.webp',
    'projetos/epoca/Hayanna/Hayanna_27.webp',
    'projetos/epoca/Hayanna/Hayanna_28.webp',
    'projetos/epoca/Hayanna/Hayanna_29.webp',
    'projetos/epoca/Hayanna/Hayanna_3.webp',
    'projetos/epoca/Hayanna/Hayanna_30.webp',
    'projetos/epoca/Hayanna/Hayanna_31.webp',
    'projetos/epoca/Hayanna/Hayanna_4.webp',
    'projetos/epoca/Hayanna/Hayanna_5.webp',
    'projetos/epoca/Hayanna/Hayanna_6.webp',
    'projetos/epoca/Hayanna/Hayanna_7.webp',
    'projetos/epoca/Hayanna/Hayanna_8.webp',
    'projetos/epoca/Hayanna/Hayanna_9.webp',
    'projetos/epoca/Heidi/Heidi_1.webp',
    'projetos/epoca/Heidi/Heidi_10.webp',
    'projetos/epoca/Heidi/Heidi_2.webp',
    'projetos/epoca/Heidi/Heidi_3.webp',
    'projetos/epoca/Heidi/Heidi_4.webp',
    'projetos/epoca/Heidi/Heidi_5.webp',
    'projetos/epoca/Heidi/Heidi_6.webp',
    'projetos/epoca/Heidi/Heidi_7.webp',
    'projetos/epoca/Heidi/Heidi_8.webp',
    'projetos/epoca/Heidi/Heidi_9.webp',
    'projetos/epoca/jessica/jessica_1.webp',
    'projetos/epoca/jessica/jessica_2.webp',
    'projetos/epoca/jessica/jessica_3.webp',
    'projetos/epoca/jessica/jessica_4.webp',
    'projetos/epoca/jessica/jessica_5.webp',
    'projetos/epoca/jessica/jessica_6.webp',
    'projetos/epoca/jessica/jessica_7.webp',
    'projetos/epoca/jessica/jessica_8.webp',
    'projetos/epoca/jessica/jessica_9.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_1.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_10.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_11.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_12.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_13.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_14.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_15.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_2.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_3.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_4.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_5.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_6.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_7.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_8.webp',
    'projetos/epoca/Nadia_Lobkov1/Nadia_Lobkov1_9.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_1.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_10.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_11.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_12.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_13.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_14.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_15.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_16.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_17.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_18.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_19.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_2.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_20.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_21.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_22.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_23.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_24.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_25.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_3.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_4.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_5.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_6.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_7.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_8.webp',
    'projetos/epoca/Nadia_Lobkov2/Ensaios Fotográficos-Editados/nadia/nadia_9.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_1.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_10.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_11.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_12.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_13.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_14.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_15.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_16.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_17.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_18.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_19.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_2.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_20.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_21.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_22.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_23.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_24.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_25.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_26.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_27.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_28.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_29.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_3.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_30.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_31.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_32.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_33.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_34.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_4.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_5.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_6.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_7.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_8.webp',
    'projetos/epoca/Nayara_Luis/Nayara_Luis_9.webp',
    'projetos/epoca/Paloma/Paloma_1.webp',
    'projetos/epoca/Paloma/Paloma_10.webp',
    'projetos/epoca/Paloma/Paloma_11.webp',
    'projetos/epoca/Paloma/Paloma_2.webp',
    'projetos/epoca/Paloma/Paloma_3.webp',
    'projetos/epoca/Paloma/Paloma_4.webp',
    'projetos/epoca/Paloma/Paloma_5.webp',
    'projetos/epoca/Paloma/Paloma_6.webp',
    'projetos/epoca/Paloma/Paloma_7.webp',
    'projetos/epoca/Paloma/Paloma_8.webp',
    'projetos/epoca/Paloma/Paloma_9.webp',
    'projetos/epoca/Val/Val_1.webp',
    'projetos/epoca/Val/Val_10.webp',
    'projetos/epoca/Val/Val_2.webp',
    'projetos/epoca/Val/Val_3.webp',
    'projetos/epoca/Val/Val_4.webp',
    'projetos/epoca/Val/Val_5.webp',
    'projetos/epoca/Val/Val_6.webp',
    'projetos/epoca/Val/Val_7.webp',
    'projetos/epoca/Val/Val_8.webp',
    'projetos/epoca/Val/Val_9.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_1.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_10.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_100.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_101.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_102.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_11.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_12.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_13.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_14.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_15.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_16.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_17.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_18.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_19.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_2.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_20.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_21.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_22.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_23.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_24.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_25.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_26.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_27.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_28.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_29.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_3.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_30.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_31.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_32.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_33.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_34.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_35.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_36.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_37.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_38.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_39.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_4.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_40.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_41.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_42.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_43.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_44.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_45.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_46.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_47.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_48.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_49.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_5.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_50.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_51.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_52.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_53.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_54.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_55.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_56.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_57.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_58.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_59.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_6.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_60.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_61.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_62.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_63.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_64.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_65.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_66.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_67.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_68.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_69.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_7.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_70.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_71.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_72.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_73.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_74.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_75.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_76.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_77.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_78.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_79.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_8.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_80.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_81.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_82.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_83.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_84.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_85.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_86.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_87.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_88.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_89.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_9.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_90.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_91.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_92.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_93.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_94.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_95.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_96.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_97.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_98.webp',
    'projetos/eventos/jheni e a cobra/jheni e a cobra_99.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_1.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_10.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_11.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_12.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_2.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_3.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_4.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_5.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_6.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_7.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_8.webp',
    'projetos/musa_day/Andressa e a cobra/Andressa e a cobra_9.webp',
    'projetos/musa_day/Daiara/Daiara_1.webp',
    'projetos/musa_day/Daiara/Daiara_2.webp',
    'projetos/musa_day/Daiara/Daiara_3.webp',
    'projetos/musa_day/Daiara/Daiara_4.webp',
    'projetos/musa_day/Daiara/Daiara_5.webp',
    'projetos/musa_day/Daiara/Daiara_6.webp',
    'projetos/musa_day/Daiara/Daiara_7.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_1.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_10.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_11.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_12.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_13.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_14.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_15.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_2.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_3.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_4.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_5.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_6.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_7.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_8.webp',
    'projetos/musa_day/Monica e a coruja/Monica e a coruja_9.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_1.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_10.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_11.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_12.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_13.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_14.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_2.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_3.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_4.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_5.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_6.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_7.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_8.webp',
    'projetos/musa_day/nadia e a cobra/nadia e a cobra_9.webp',
    'projetos/MUSAS MÍSTICAS ENSAIO EXTERNO/Malu/Malu_1.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_1.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_10.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_2.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_3.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_4.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_5.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_6.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_7.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_8.webp',
    'projetos/personalizados/Bella de Moraes/Bella de Moraes_9.webp',
    'projetos/personalizados/jaci/jaci_1.webp',
    'projetos/personalizados/jaci/jaci_10.webp',
    'projetos/personalizados/jaci/jaci_11.webp',
    'projetos/personalizados/jaci/jaci_12.webp',
    'projetos/personalizados/jaci/jaci_13.webp',
    'projetos/personalizados/jaci/jaci_14.webp',
    'projetos/personalizados/jaci/jaci_15.webp',
    'projetos/personalizados/jaci/jaci_16.webp',
    'projetos/personalizados/jaci/jaci_2.webp',
    'projetos/personalizados/jaci/jaci_3.webp',
    'projetos/personalizados/jaci/jaci_4.webp',
    'projetos/personalizados/jaci/jaci_5.webp',
    'projetos/personalizados/jaci/jaci_6.webp',
    'projetos/personalizados/jaci/jaci_7.webp',
    'projetos/personalizados/jaci/jaci_8.webp',
    'projetos/personalizados/jaci/jaci_9.webp',
    'projetos/personalizados/keshy/keshy_1.webp',
    'projetos/personalizados/keshy/keshy_10.webp',
    'projetos/personalizados/keshy/keshy_11.webp',
    'projetos/personalizados/keshy/keshy_12.webp',
    'projetos/personalizados/keshy/keshy_13.webp',
    'projetos/personalizados/keshy/keshy_14.webp',
    'projetos/personalizados/keshy/keshy_15.webp',
    'projetos/personalizados/keshy/keshy_16.webp',
    'projetos/personalizados/keshy/keshy_17.webp',
    'projetos/personalizados/keshy/keshy_18.webp',
    'projetos/personalizados/keshy/keshy_19.webp',
    'projetos/personalizados/keshy/keshy_2.webp',
    'projetos/personalizados/keshy/keshy_20.webp',
    'projetos/personalizados/keshy/keshy_21.webp',
    'projetos/personalizados/keshy/keshy_22.webp',
    'projetos/personalizados/keshy/keshy_23.webp',
    'projetos/personalizados/keshy/keshy_24.webp',
    'projetos/personalizados/keshy/keshy_25.webp',
    'projetos/personalizados/keshy/keshy_26.webp',
    'projetos/personalizados/keshy/keshy_27.webp',
    'projetos/personalizados/keshy/keshy_28.webp',
    'projetos/personalizados/keshy/keshy_29.webp',
    'projetos/personalizados/keshy/keshy_3.webp',
    'projetos/personalizados/keshy/keshy_30.webp',
    'projetos/personalizados/keshy/keshy_31.webp',
    'projetos/personalizados/keshy/keshy_32.webp',
    'projetos/personalizados/keshy/keshy_33.webp',
    'projetos/personalizados/keshy/keshy_34.webp',
    'projetos/personalizados/keshy/keshy_35.webp',
    'projetos/personalizados/keshy/keshy_36.webp',
    'projetos/personalizados/keshy/keshy_4.webp',
    'projetos/personalizados/keshy/keshy_5.webp',
    'projetos/personalizados/keshy/keshy_6.webp',
    'projetos/personalizados/keshy/keshy_7.webp',
    'projetos/personalizados/keshy/keshy_8.webp',
    'projetos/personalizados/keshy/keshy_9.webp',
    'projetos/personalizados/Lara/Lara_1.webp',
    'projetos/personalizados/Lara/Lara_10.webp',
    'projetos/personalizados/Lara/Lara_11.webp',
    'projetos/personalizados/Lara/Lara_12.webp',
    'projetos/personalizados/Lara/Lara_13.webp',
    'projetos/personalizados/Lara/Lara_14.webp',
    'projetos/personalizados/Lara/Lara_15.webp',
    'projetos/personalizados/Lara/Lara_16.webp',
    'projetos/personalizados/Lara/Lara_17.webp',
    'projetos/personalizados/Lara/Lara_18.webp',
    'projetos/personalizados/Lara/Lara_19.webp',
    'projetos/personalizados/Lara/Lara_2.webp',
    'projetos/personalizados/Lara/Lara_20.webp',
    'projetos/personalizados/Lara/Lara_21.webp',
    'projetos/personalizados/Lara/Lara_22.webp',
    'projetos/personalizados/Lara/Lara_3.webp',
    'projetos/personalizados/Lara/Lara_4.webp',
    'projetos/personalizados/Lara/Lara_5.webp',
    'projetos/personalizados/Lara/Lara_6.webp',
    'projetos/personalizados/Lara/Lara_7.webp',
    'projetos/personalizados/Lara/Lara_8.webp',
    'projetos/personalizados/Lara/Lara_9.webp',
    'projetos/personalizados/Monica/Monica_1.webp',
    'projetos/personalizados/Monica/Monica_10.webp',
    'projetos/personalizados/Monica/Monica_11.webp',
    'projetos/personalizados/Monica/Monica_12.webp',
    'projetos/personalizados/Monica/Monica_13.webp',
    'projetos/personalizados/Monica/Monica_14.webp',
    'projetos/personalizados/Monica/Monica_15.webp',
    'projetos/personalizados/Monica/Monica_2.webp',
    'projetos/personalizados/Monica/Monica_3.webp',
    'projetos/personalizados/Monica/Monica_4.webp',
    'projetos/personalizados/Monica/Monica_5.webp',
    'projetos/personalizados/Monica/Monica_6.webp',
    'projetos/personalizados/Monica/Monica_7.webp',
    'projetos/personalizados/Monica/Monica_8.webp',
    'projetos/personalizados/Monica/Monica_9.webp',
  ],
};

export default manifest;
